# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20180321_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='description'),
        ),
    ]
